version: '3'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 8081:8081
    volumes:
      - mongodb-volume:/data/db

volumes:
  mongodb-volume:
