version: '3'
services:

  ### ES
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.2
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
      - vm.max_map_count=1048576
      - cluster.initial_master_nodes=es

volumes:
  esdata01:
