version: '3'
services:

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-volume:/var/jenkins_home

volumes:
  jenkins-volume:
