version: '3'
services:
  jenkins-docker:
    privileged: true
    image: docker:dind
    ports:
      - "3000:3000"
      - "2376:2376"
    networks:
      jenkins:
        aliases:
          - docker
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-certs:/certs/client
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-certs:/certs/client

  jenkins-blueocean:
    depends_on:
      - jenkins-docker
    image: myjenkins-blueocean:1.1
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      jenkins:
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-certs:/certs/client:ro
      - $HOME:/home  # required only to access locally cloned code
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1

volumes:
  jenkins-certs:
  jenkins-data:

networks:
  jenkins:
    external: true
    name: jenkins

